title: Resources
description: A collection of resources for graduate students
theme: just-the-docs

url: https://zeyuyang8.github.io/resources

aux_links:
  Template Repository: https://github.com/zeyuyang8/graduate-student-resources

favicon_ico: "/assets/images/favicon.ico"

math: katex
